// carpool-vue/src/views/CaptainSignup.vue
<template>
  <div class="signup-container">
    <form @submit.prevent="submitHandler" class="form">
      <h3 class="form-title">Captain Signup</h3>

      <div class="name-inputs">
        <label class="form-label">What's our captain's name</label>
        <div class="name-fields">
          <input
            id="firstName"
            required
            type="text"
            placeholder="First Name"
            v-model="firstName"
            class="input first-name"
          />
          <input
            id="lastName"
            required
            type="text"
            placeholder="Last Name"
            v-model="lastName"
            class="input"
          />
        </div>
      </div>

      <div class="email-inputs">
        <label class="form-label">What's our captain's Email</label>
        <input
          required
          type="email"
          placeholder="Email"
          v-model="email"
          class="input full-width"
        />
      </div>

      <div class="password-input">
        <label class="form-label">Enter Password</label>
        <input
          required
          type="password"
          placeholder="Password"
          v-model="password"
          class="input full-width"
        />
      </div>

      <h4 class="vehicle-title">Vehicle Information</h4>
      <div class="vehicle-inputs">
        <input
          required
          type="text"
          placeholder="Vehicle Color"
          v-model="vehicleColor"
          class="input vehicle-color"
        />
        <input
          required
          type="text"
          placeholder="Vehicle Plate"
          v-model="vehiclePlate"
          class="input"
        />
      </div>
      <div class="vehicle-inputs">
        <input
          required
          type="number"
          placeholder="Vehicle Capacity"
          v-model="vehicleCapacity"
          class="input vehicle-capacity"
        />
        <select required v-model="vehicleType" class="input select-input">
          <option value="" disabled>Select Vehicle Type</option>
          <option value="car">Car</option>
          <option value="auto">Auto</option>
          <option value="moto">Moto</option>
        </select>
      </div>

      <button type="submit" class="submit-button">
        Create Captain Account
      </button>

      <p class="login-link">
        Already have an account?
        <router-link to="/captain-login" class="text-blue-600"
          >Login here</router-link
        >
      </p>

      <p class="privacy-policy">
        This site is protected by reCAPTCHA and the
        <span class="underline">Google Privacy Policy</span> and
        <span class="underline">Terms of Service apply</span>.
      </p>
    </form>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'CaptainSignup',
  setup() {
    const firstName = ref('');
    const lastName = ref('');
    const email = ref('');
    const password = ref('');
    const vehicleColor = ref('');
    const vehiclePlate = ref('');
    const vehicleCapacity = ref('');
    const vehicleType = ref('');

    const submitHandler = () => {
      if (firstName.value && lastName.value && email.value && password.value 
          && vehicleColor.value && vehiclePlate.value 
          && vehicleCapacity.value && vehicleType.value) {
        const captainData = {
          firstName: firstName.value,
          lastName: lastName.value,
          email: email.value,
          vehicleColor: vehicleColor.value,
          vehiclePlate: vehiclePlate.value,
          vehicleCapacity: vehicleCapacity.value,
          vehicleType: vehicleType.value
        };

        console.log('Captain Signup Data:', captainData);
        
        // TODO: Implement API call here
        
        // Reset form
        resetForm();
      } else {
        alert('Please fill out all fields');
      }
    };

    const resetForm = () => {
      firstName.value = '';
      lastName.value = '';
      email.value = '';
      password.value = '';
      vehicleColor.value = '';
      vehiclePlate.value = '';
      vehicleCapacity.value = '';
      vehicleType.value = '';
    };

    return {
      firstName,
      lastName,
      email,
      password,
      vehicleColor,
      vehiclePlate,
      vehicleCapacity,
      vehicleType,
      submitHandler
    };
  }
};
</script>

<style scoped>
.signup-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  padding: 20px;
  background-color: #f8f9fa;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, sans-serif;
}

.form {
  background: #ffffff;
  padding: 2rem;
  border-radius: 10px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  width: 100%;
  max-width: 500px;
}

.form-title {
  font-size: 34px;
  font-weight: 600;
  margin-bottom: 30px;
  text-align: center;
}

.form-label {
  font-weight: 450;
}

.name-inputs,
.email-inputs,
.password-input {
  margin-bottom: 20px;
}

.name-fields {
  display: flex;
  justify-content: space-between;
}

.input {
  width: 100%;
  max-width: 48%;
  padding: 12px;
  border: 1px solid #ddd;
  border-radius: 5px;
  font-size: 1rem;
  background-color: #f8f8f8;
}

.input.first-name {
  margin-right: 10px; /* Adjust the value for desired spacing */
}

.full-width {
  max-width: 95%; /* Full width for email and password inputs */
}

.input.vehicle-color {
  margin-right: 10px; /* Adjust the value for desired spacing */
}

.input.vehicle-capacity {
  margin-right: 10px; /* Adjust the value for desired spacing */
}

.vehicle-inputs {
  display: flex;
  justify-content: space-between;
  margin-bottom: 1rem;
}

.select-input {
  appearance: none;
  background-color: #f8f8f8;
}

.submit-button {
  width: 100%;
  border: none;
  border-radius: 5px;
  padding: 12px;
  background-color: #333;
  color: white;
  font-size: 1rem;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.3s;
}

.submit-button:hover {
  background-color: #444;
}

.login-link {
  text-align: center;
  margin-top: 20px;
}

.privacy-policy {
  text-align: center;
  font-size: 12px;
  margin-top: 30px;
  color: #666;
}

.underline {
  text-decoration: underline;
}
</style>

// frontend/src/pages/CaptainSignup.jsx
import React, { useState } from 'react'
import { Link } from 'react-router-dom'

const CaptainSignup = () => {

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')

  const [vehicleColor, setVehicleColor] = useState('')
  const [vehiclePlate, setVehiclePlate] = useState('')
  const [vehicleCapacity, setVehicleCapacity] = useState('')
  const [vehicleType, setVehicleType] = useState('')


  const [captainData, setCaptainData] = useState({})


  const submitHandler = async (e) => {
    e.preventDefault()
    setCaptainData({
      fullName: {
        firstname: firstName,
        lastname: lastName
      },
      email: email,
      password: password,
      vehicle: {
        color: vehicleColor,
        plate: vehiclePlate,
        capacity: vehicleCapacity,
        vehicleType: vehicleType
      }
    })

    console.log(captainData)

    setEmail('')
    setFirstName('')
    setLastName('')
    setPassword('')
    setVehicleColor('')
    setVehiclePlate('')
    setVehicleCapacity('')
    setVehicleType('')

  }
  return (
    <div className='py-5 px-5 h-screen flex flex-col justify-between'>
      <div>

        <form onSubmit={(e) => {
          submitHandler(e)
        }}>

          <h3 className='text-lg w-full  font-medium mb-2'>What's our Captain's name</h3>
          <div className='flex gap-4 mb-7'>
            <input
              required
              className='bg-[#eeeeee] w-1/2 rounded-lg px-4 py-2 border  text-lg placeholder:text-base'
              type="text"
              placeholder='First name'
              value={firstName}
              onChange={(e) => {
                setFirstName(e.target.value)
              }}
            />
            <input
              required
              className='bg-[#eeeeee] w-1/2  rounded-lg px-4 py-2 border  text-lg placeholder:text-base'
              type="text"
              placeholder='Last name'
              value={lastName}
              onChange={(e) => {
                setLastName(e.target.value)
              }}
            />
          </div>

          <h3 className='text-lg font-medium mb-2'>What's our Captain's email</h3>
          <input
            required
            value={email}
            onChange={(e) => {
              setEmail(e.target.value)
            }}
            className='bg-[#eeeeee] mb-7 rounded-lg px-4 py-2 border w-full text-lg placeholder:text-base'
            type="email"
            placeholder='email@example.com'
          />

          <h3 className='text-lg font-medium mb-2'>Enter Password</h3>

          <input
            className='bg-[#eeeeee] mb-7 rounded-lg px-4 py-2 border w-full text-lg placeholder:text-base'
            value={password}
            onChange={(e) => {
              setPassword(e.target.value)
            }}
            required type="password"
            placeholder='password'
          />

          <h3 className='text-lg font-medium mb-2'>Vehicle Information</h3>
          <div className='flex gap-4 mb-7'>
            <input
              required
              className='bg-[#eeeeee] w-1/2 rounded-lg px-4 py-2 border text-lg placeholder:text-base'
              type="text"
              placeholder='Vehicle Color'
              value={vehicleColor}
              onChange={(e) => {
                setVehicleColor(e.target.value)
              }}
            />
            <input
              required
              className='bg-[#eeeeee] w-1/2 rounded-lg px-4 py-2 border text-lg placeholder:text-base'
              type="text"
              placeholder='Vehicle Plate'
              value={vehiclePlate}
              onChange={(e) => {
                setVehiclePlate(e.target.value)
              }}
            />
          </div>
          <div className='flex gap-4 mb-7'>
            <input
              required
              className='bg-[#eeeeee] w-1/2 rounded-lg px-4 py-2 border text-lg placeholder:text-base'
              type="number"
              placeholder='Vehicle Capacity'
              value={vehicleCapacity}
              onChange={(e) => {
                setVehicleCapacity(e.target.value)
              }}
            />
            <select
              required
              className='bg-[#eeeeee] w-1/2 rounded-lg px-4 py-2 border text-lg placeholder:text-base'
              value={vehicleType}
              onChange={(e) => {
                setVehicleType(e.target.value)
              }}
            >
              <option value="" disabled>Select Vehicle Type</option>
              <option value="car">Car</option>
              <option value="auto">Auto</option>
              <option value="moto">Moto</option>
            </select>
          </div>

          <button
            className='bg-[#111] text-white font-semibold mb-3 rounded-lg px-4 py-2 w-full text-lg placeholder:text-base'
          >Create Captain Account</button>

        </form>
        <p className='text-center'>Already have a account? <Link to='/captain-login' className='text-blue-600'>Login here</Link></p>
      </div>
      <div>
        <p className='text-[10px] mt-6 leading-tight'>This site is protected by reCAPTCHA and the <span className='underline'>Google Privacy
          Policy</span> and <span className='underline'>Terms of Service apply</span>.</p>
      </div>
    </div>
  )
}

export default CaptainSignup
